/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PersistentHotelVisibility = IDL.Record({
  'isPaid' : IDL.Bool,
  'isActive' : IDL.Bool,
  'isDummyHotel' : IDL.Bool,
});
export const MapLocation = IDL.Record({
  'mapLink' : IDL.Text,
  'address' : IDL.Text,
});
export const RoomCurrency = IDL.Variant({
  'EUR' : IDL.Null,
  'IDR' : IDL.Null,
  'SGD' : IDL.Null,
  'USD' : IDL.Null,
});
export const RoomInventory = IDL.Record({
  'pricePerNight' : IDL.Nat,
  'currency' : RoomCurrency,
  'promo' : IDL.Opt(IDL.Text),
  'roomType' : IDL.Text,
  'photos' : IDL.Vec(IDL.Text),
});
export const HotelClassification = IDL.Variant({
  'threeStar' : IDL.Null,
  'oneStar' : IDL.Null,
  'fiveStar' : IDL.Null,
  'fourStar' : IDL.Null,
  'jasmine' : IDL.Null,
  'twoStar' : IDL.Null,
});
export const HotelProfile = IDL.Record({
  'country' : IDL.Text,
  'logo' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'payment_instructions' : IDL.Opt(IDL.Text),
  'location' : MapLocation,
  'rooms' : IDL.Vec(RoomInventory),
  'classification' : HotelClassification,
});
export const AdminHotelVisibilityView = IDL.Record({
  'hotel' : IDL.Principal,
  'visibility' : PersistentHotelVisibility,
  'profile' : IDL.Opt(HotelProfile),
});
export const AdminRecoveryDiagnostics = IDL.Record({
  'accessControlInitialized' : IDL.Bool,
  'callerIsAdmin' : IDL.Bool,
  'caller' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CreateBookingInput = IDL.Record({
  'hotel' : IDL.Principal,
  'room_type' : IDL.Text,
  'checkInDate' : Time,
  'guest' : IDL.Principal,
  'checkOutDate' : Time,
  'guests' : IDL.Nat,
});
export const PaymentOption = IDL.Variant({
  'dana' : IDL.Null,
  'gopay' : IDL.Null,
  'paypal' : IDL.Null,
});
export const CreateStayRecordInput = IDL.Record({
  'hotelName' : IDL.Text,
  'hotel' : IDL.Principal,
  'checkInDate' : Time,
  'guest' : IDL.Principal,
  'checkOutDate' : IDL.Opt(Time),
});
export const AccountStatus = IDL.Record({
  'userProfileExists' : IDL.Bool,
  'callerIsAdmin' : IDL.Bool,
  'callerIsInvited' : IDL.Bool,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'hotelName' : IDL.Text,
  'hotel' : IDL.Principal,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'room_type' : IDL.Text,
  'checkInDate' : Time,
  'guest' : IDL.Principal,
  'checkOutDate' : Time,
  'guests' : IDL.Nat,
});
export const HotelProfileWithPrincipal = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : HotelProfile,
});
export const InviteToken = IDL.Record({
  'token' : IDL.Text,
  'isConsumed' : IDL.Bool,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : PaymentStatus,
  'option' : PaymentOption,
  'user' : IDL.Principal,
  'reference' : IDL.Text,
  'amount' : IDL.Nat,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const StayRecord = IDL.Record({
  'id' : IDL.Nat,
  'hotelName' : IDL.Text,
  'hotel' : IDL.Principal,
  'createdAt' : Time,
  'checkInDate' : Time,
  'guest' : IDL.Principal,
  'checkOutDate' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const HealthStatus = IDL.Record({ 'ok' : IDL.Bool, 'timestamp' : Time });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetAllHotelVisibilityStats' : IDL.Func(
      [],
      [IDL.Vec(AdminHotelVisibilityView)],
      ['query'],
    ),
  'adminRecoveryDiagnostics' : IDL.Func(
      [],
      [AdminRecoveryDiagnostics],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'checkInviteToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'confirmBooking' : IDL.Func([IDL.Nat], [], []),
  'confirmPaymentRequest' : IDL.Func([IDL.Text], [], []),
  'consumeInviteToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createBookingRequest' : IDL.Func([CreateBookingInput], [IDL.Nat], []),
  'createPaymentRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, PaymentOption],
      [IDL.Text],
      [],
    ),
  'createStayRecord' : IDL.Func([CreateStayRecordInput], [IDL.Nat], []),
  'deleteRoomInventory' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'generateHotelInviteToken' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAccountStatus' : IDL.Func([], [AccountStatus], ['query']),
  'getAllBookingRequests' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getAllHotelsWithPrincipals' : IDL.Func(
      [],
      [IDL.Vec(HotelProfileWithPrincipal)],
      ['query'],
    ),
  'getAllInviteTokens' : IDL.Func([], [IDL.Vec(InviteToken)], ['query']),
  'getAllPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getBookingRequest' : IDL.Func([IDL.Nat], [BookingRequest], ['query']),
  'getCallerPendingBookings' : IDL.Func(
      [],
      [IDL.Vec(BookingRequest)],
      ['query'],
    ),
  'getCallerProcessingBookings' : IDL.Func(
      [],
      [IDL.Vec(BookingRequest)],
      ['query'],
    ),
  'getCallerStayHistory' : IDL.Func([], [IDL.Vec(StayRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHotelBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getHotelPendingBookings' : IDL.Func(
      [],
      [IDL.Vec(BookingRequest)],
      ['query'],
    ),
  'getHotelProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(HotelProfile)],
      ['query'],
    ),
  'getHotelVisibility' : IDL.Func(
      [IDL.Principal],
      [PersistentHotelVisibility],
      ['query'],
    ),
  'getHotelsByCountry' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HotelProfile)],
      ['query'],
    ),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getPaymentRequest' : IDL.Func([IDL.Text], [PaymentRequest], ['query']),
  'getTestingMode' : IDL.Func([], [IDL.Bool], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'health' : IDL.Func([], [HealthStatus], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerInvited' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectBooking' : IDL.Func([IDL.Nat], [], []),
  'rejectPaymentRequest' : IDL.Func([IDL.Text], [], []),
  'restoreAdminAccess' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveHotelProfile' : IDL.Func([HotelProfile], [], []),
  'setHotelPaymentStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'setHotelVisibility' : IDL.Func([IDL.Principal, IDL.Bool, IDL.Bool], [], []),
  'setTestingMode' : IDL.Func([IDL.Bool], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateRoomInventory' : IDL.Func([IDL.Principal, RoomInventory], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PersistentHotelVisibility = IDL.Record({
    'isPaid' : IDL.Bool,
    'isActive' : IDL.Bool,
    'isDummyHotel' : IDL.Bool,
  });
  const MapLocation = IDL.Record({
    'mapLink' : IDL.Text,
    'address' : IDL.Text,
  });
  const RoomCurrency = IDL.Variant({
    'EUR' : IDL.Null,
    'IDR' : IDL.Null,
    'SGD' : IDL.Null,
    'USD' : IDL.Null,
  });
  const RoomInventory = IDL.Record({
    'pricePerNight' : IDL.Nat,
    'currency' : RoomCurrency,
    'promo' : IDL.Opt(IDL.Text),
    'roomType' : IDL.Text,
    'photos' : IDL.Vec(IDL.Text),
  });
  const HotelClassification = IDL.Variant({
    'threeStar' : IDL.Null,
    'oneStar' : IDL.Null,
    'fiveStar' : IDL.Null,
    'fourStar' : IDL.Null,
    'jasmine' : IDL.Null,
    'twoStar' : IDL.Null,
  });
  const HotelProfile = IDL.Record({
    'country' : IDL.Text,
    'logo' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'payment_instructions' : IDL.Opt(IDL.Text),
    'location' : MapLocation,
    'rooms' : IDL.Vec(RoomInventory),
    'classification' : HotelClassification,
  });
  const AdminHotelVisibilityView = IDL.Record({
    'hotel' : IDL.Principal,
    'visibility' : PersistentHotelVisibility,
    'profile' : IDL.Opt(HotelProfile),
  });
  const AdminRecoveryDiagnostics = IDL.Record({
    'accessControlInitialized' : IDL.Bool,
    'callerIsAdmin' : IDL.Bool,
    'caller' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CreateBookingInput = IDL.Record({
    'hotel' : IDL.Principal,
    'room_type' : IDL.Text,
    'checkInDate' : Time,
    'guest' : IDL.Principal,
    'checkOutDate' : Time,
    'guests' : IDL.Nat,
  });
  const PaymentOption = IDL.Variant({
    'dana' : IDL.Null,
    'gopay' : IDL.Null,
    'paypal' : IDL.Null,
  });
  const CreateStayRecordInput = IDL.Record({
    'hotelName' : IDL.Text,
    'hotel' : IDL.Principal,
    'checkInDate' : Time,
    'guest' : IDL.Principal,
    'checkOutDate' : IDL.Opt(Time),
  });
  const AccountStatus = IDL.Record({
    'userProfileExists' : IDL.Bool,
    'callerIsAdmin' : IDL.Bool,
    'callerIsInvited' : IDL.Bool,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'hotelName' : IDL.Text,
    'hotel' : IDL.Principal,
    'createdAt' : Time,
    'lastUpdated' : Time,
    'room_type' : IDL.Text,
    'checkInDate' : Time,
    'guest' : IDL.Principal,
    'checkOutDate' : Time,
    'guests' : IDL.Nat,
  });
  const HotelProfileWithPrincipal = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : HotelProfile,
  });
  const InviteToken = IDL.Record({
    'token' : IDL.Text,
    'isConsumed' : IDL.Bool,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentStatus,
    'option' : PaymentOption,
    'user' : IDL.Principal,
    'reference' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const StayRecord = IDL.Record({
    'id' : IDL.Nat,
    'hotelName' : IDL.Text,
    'hotel' : IDL.Principal,
    'createdAt' : Time,
    'checkInDate' : Time,
    'guest' : IDL.Principal,
    'checkOutDate' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const HealthStatus = IDL.Record({ 'ok' : IDL.Bool, 'timestamp' : Time });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetAllHotelVisibilityStats' : IDL.Func(
        [],
        [IDL.Vec(AdminHotelVisibilityView)],
        ['query'],
      ),
    'adminRecoveryDiagnostics' : IDL.Func(
        [],
        [AdminRecoveryDiagnostics],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'checkInviteToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'confirmBooking' : IDL.Func([IDL.Nat], [], []),
    'confirmPaymentRequest' : IDL.Func([IDL.Text], [], []),
    'consumeInviteToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createBookingRequest' : IDL.Func([CreateBookingInput], [IDL.Nat], []),
    'createPaymentRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, PaymentOption],
        [IDL.Text],
        [],
      ),
    'createStayRecord' : IDL.Func([CreateStayRecordInput], [IDL.Nat], []),
    'deleteRoomInventory' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'generateHotelInviteToken' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAccountStatus' : IDL.Func([], [AccountStatus], ['query']),
    'getAllBookingRequests' : IDL.Func(
        [],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getAllHotelsWithPrincipals' : IDL.Func(
        [],
        [IDL.Vec(HotelProfileWithPrincipal)],
        ['query'],
      ),
    'getAllInviteTokens' : IDL.Func([], [IDL.Vec(InviteToken)], ['query']),
    'getAllPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getBookingRequest' : IDL.Func([IDL.Nat], [BookingRequest], ['query']),
    'getCallerPendingBookings' : IDL.Func(
        [],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getCallerProcessingBookings' : IDL.Func(
        [],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getCallerStayHistory' : IDL.Func([], [IDL.Vec(StayRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHotelBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getHotelPendingBookings' : IDL.Func(
        [],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getHotelProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(HotelProfile)],
        ['query'],
      ),
    'getHotelVisibility' : IDL.Func(
        [IDL.Principal],
        [PersistentHotelVisibility],
        ['query'],
      ),
    'getHotelsByCountry' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HotelProfile)],
        ['query'],
      ),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getPaymentRequest' : IDL.Func([IDL.Text], [PaymentRequest], ['query']),
    'getTestingMode' : IDL.Func([], [IDL.Bool], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'health' : IDL.Func([], [HealthStatus], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerInvited' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectBooking' : IDL.Func([IDL.Nat], [], []),
    'rejectPaymentRequest' : IDL.Func([IDL.Text], [], []),
    'restoreAdminAccess' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveHotelProfile' : IDL.Func([HotelProfile], [], []),
    'setHotelPaymentStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'setHotelVisibility' : IDL.Func(
        [IDL.Principal, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'setTestingMode' : IDL.Func([IDL.Bool], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateRoomInventory' : IDL.Func([IDL.Principal, RoomInventory], [], []),
  });
};

export const init = ({ IDL }) => { return []; };