/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountStatus {
  'userProfileExists' : boolean,
  'callerIsAdmin' : boolean,
  'callerIsInvited' : boolean,
}
export interface AdminHotelVisibilityView {
  'hotel' : Principal,
  'visibility' : PersistentHotelVisibility,
  'profile' : [] | [HotelProfile],
}
export interface AdminRecoveryDiagnostics {
  'accessControlInitialized' : boolean,
  'callerIsAdmin' : boolean,
  'caller' : Principal,
}
export interface BookingRequest {
  'id' : bigint,
  'status' : BookingStatus,
  'hotelName' : string,
  'hotel' : Principal,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'checkInDate' : Time,
  'guest' : Principal,
  'checkOutDate' : Time,
  'guests' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null };
export interface CreateBookingInput {
  'hotel' : Principal,
  'checkInDate' : Time,
  'guest' : Principal,
  'checkOutDate' : Time,
  'guests' : bigint,
}
export interface CreateStayRecordInput {
  'hotelName' : string,
  'hotel' : Principal,
  'checkInDate' : Time,
  'guest' : Principal,
  'checkOutDate' : [] | [Time],
}
export interface HealthStatus { 'ok' : boolean, 'timestamp' : Time }
export type HotelClassification = { 'threeStar' : null } |
  { 'oneStar' : null } |
  { 'fiveStar' : null } |
  { 'fourStar' : null } |
  { 'jasmine' : null } |
  { 'twoStar' : null };
export interface HotelProfile {
  'country' : string,
  'logo' : [] | [string],
  'name' : string,
  'location' : MapLocation,
  'rooms' : Array<RoomInventory>,
  'classification' : HotelClassification,
}
export interface HotelProfileWithPrincipal {
  'principal' : Principal,
  'profile' : HotelProfile,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface InviteToken { 'token' : string, 'isConsumed' : boolean }
export interface MapLocation { 'mapLink' : string, 'address' : string }
export type PaymentOption = { 'dana' : null } |
  { 'gopay' : null } |
  { 'paypal' : null };
export interface PaymentRequest {
  'id' : string,
  'status' : PaymentStatus,
  'option' : PaymentOption,
  'user' : Principal,
  'reference' : string,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null };
export interface PersistentHotelVisibility {
  'isPaid' : boolean,
  'isActive' : boolean,
  'isDummyHotel' : boolean,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface RoomInventory {
  'pricePerNight' : bigint,
  'promo' : [] | [string],
  'roomType' : string,
  'photos' : Array<string>,
}
export interface StayRecord {
  'id' : bigint,
  'hotelName' : string,
  'hotel' : Principal,
  'createdAt' : Time,
  'checkInDate' : Time,
  'guest' : Principal,
  'checkOutDate' : [] | [Time],
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetAllHotelVisibilityStats' : ActorMethod<
    [],
    Array<AdminHotelVisibilityView>
  >,
  'adminRecoveryDiagnostics' : ActorMethod<[], AdminRecoveryDiagnostics>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'checkInviteToken' : ActorMethod<[string], boolean>,
  'confirmBooking' : ActorMethod<[bigint], undefined>,
  'confirmPaymentRequest' : ActorMethod<[string], undefined>,
  'consumeInviteToken' : ActorMethod<[string], boolean>,
  'createBookingRequest' : ActorMethod<[CreateBookingInput], bigint>,
  'createBookingRequestWithTesting' : ActorMethod<[CreateBookingInput], bigint>,
  'createPaymentRequest' : ActorMethod<
    [bigint, string, string, PaymentOption],
    string
  >,
  'createStayRecord' : ActorMethod<[CreateStayRecordInput], bigint>,
  'deleteRoomInventory' : ActorMethod<[Principal, string], undefined>,
  'generateHotelInviteToken' : ActorMethod<[string], string>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAccountStatus' : ActorMethod<[], AccountStatus>,
  'getAllBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'getAllHotelsWithPrincipals' : ActorMethod<
    [],
    Array<HotelProfileWithPrincipal>
  >,
  'getAllInviteTokens' : ActorMethod<[], Array<InviteToken>>,
  'getAllPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getBookingRequest' : ActorMethod<[bigint], BookingRequest>,
  'getCallerPendingBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getCallerProcessingBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getCallerStayHistory' : ActorMethod<[], Array<StayRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHotelBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getHotelPendingBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getHotelProfile' : ActorMethod<[Principal], [] | [HotelProfile]>,
  'getHotelVisibility' : ActorMethod<[Principal], PersistentHotelVisibility>,
  'getHotelsByCountry' : ActorMethod<[string], Array<HotelProfile>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getPaymentRequest' : ActorMethod<[string], PaymentRequest>,
  'getTestingMode' : ActorMethod<[], boolean>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'health' : ActorMethod<[], HealthStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerInvited' : ActorMethod<[], boolean>,
  'rejectBooking' : ActorMethod<[bigint], undefined>,
  'rejectPaymentRequest' : ActorMethod<[string], undefined>,
  'restoreAdminAccess' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveHotelProfile' : ActorMethod<[HotelProfile], undefined>,
  'setHotelPaymentStatus' : ActorMethod<[Principal, boolean], undefined>,
  'setHotelVisibility' : ActorMethod<[Principal, boolean, boolean], undefined>,
  'setTestingMode' : ActorMethod<[boolean], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateRoomInventory' : ActorMethod<[Principal, RoomInventory], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];