/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface CreateStayRecordInput {
    hotelName: string;
    hotel: Principal;
    checkInDate: Time;
    guest: Principal;
    checkOutDate?: Time;
}
export interface HotelProfileWithPrincipal {
    principal: Principal;
    profile: HotelProfile;
}
export interface CreateBookingInput {
    hotel: Principal;
    room_type: string;
    checkInDate: Time;
    guest: Principal;
    checkOutDate: Time;
    guests: bigint;
}
export interface BookingRequest {
    id: bigint;
    status: BookingStatus;
    hotelName: string;
    hotel: Principal;
    createdAt: Time;
    lastUpdated: Time;
    room_type: string;
    checkInDate: Time;
    guest: Principal;
    checkOutDate: Time;
    guests: bigint;
}
export interface AdminRecoveryDiagnostics {
    accessControlInitialized: boolean;
    callerIsAdmin: boolean;
    caller: Principal;
}
export interface HealthStatus {
    ok: boolean;
    timestamp: Time;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface StayRecord {
    id: bigint;
    hotelName: string;
    hotel: Principal;
    createdAt: Time;
    checkInDate: Time;
    guest: Principal;
    checkOutDate?: Time;
}
export interface PersistentHotelVisibility {
    isPaid: boolean;
    isActive: boolean;
    isDummyHotel: boolean;
}
export interface AccountStatus {
    userProfileExists: boolean;
    callerIsAdmin: boolean;
    callerIsInvited: boolean;
}
export interface InviteToken {
    token: string;
    isConsumed: boolean;
}
export interface RoomInventory {
    pricePerNight: bigint;
    currency: RoomCurrency;
    promo?: string;
    roomType: string;
    photos: Array<string>;
}
export interface HotelProfile {
    country: string;
    logo?: string;
    name: string;
    payment_instructions?: string;
    location: MapLocation;
    rooms: Array<RoomInventory>;
    classification: HotelClassification;
}
export interface MapLocation {
    mapLink: string;
    address: string;
}
export interface PaymentRequest {
    id: string;
    status: PaymentStatus;
    option: PaymentOption;
    user: Principal;
    reference: string;
    amount: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface AdminHotelVisibilityView {
    hotel: Principal;
    visibility: PersistentHotelVisibility;
    profile?: HotelProfile;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    rejected = "rejected",
    confirmed = "confirmed"
}
export enum HotelClassification {
    threeStar = "threeStar",
    oneStar = "oneStar",
    fiveStar = "fiveStar",
    fourStar = "fourStar",
    jasmine = "jasmine",
    twoStar = "twoStar"
}
export enum PaymentOption {
    dana = "dana",
    gopay = "gopay",
    paypal = "paypal"
}
export enum PaymentStatus {
    pending = "pending",
    rejected = "rejected",
    confirmed = "confirmed"
}
export enum RoomCurrency {
    EUR = "EUR",
    IDR = "IDR",
    SGD = "SGD",
    USD = "USD"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminGetAllHotelVisibilityStats(): Promise<Array<AdminHotelVisibilityView>>;
    adminRecoveryDiagnostics(): Promise<AdminRecoveryDiagnostics>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBooking(id: bigint): Promise<void>;
    checkInviteToken(token: string): Promise<boolean>;
    confirmBooking(id: bigint): Promise<void>;
    confirmPaymentRequest(id: string): Promise<void>;
    consumeInviteToken(token: string): Promise<boolean>;
    createBookingRequest(input: CreateBookingInput): Promise<bigint>;
    createPaymentRequest(amount: bigint, id: string, reference: string, option: PaymentOption): Promise<string>;
    createStayRecord(input: CreateStayRecordInput): Promise<bigint>;
    deleteRoomInventory(hotelPrincipal: Principal, roomType: string): Promise<void>;
    generateHotelInviteToken(token: string): Promise<string>;
    generateInviteCode(): Promise<string>;
    getAccountStatus(): Promise<AccountStatus>;
    getAllBookingRequests(): Promise<Array<BookingRequest>>;
    getAllHotelsWithPrincipals(): Promise<Array<HotelProfileWithPrincipal>>;
    getAllInviteTokens(): Promise<Array<InviteToken>>;
    getAllPaymentRequests(): Promise<Array<PaymentRequest>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getBookingRequest(id: bigint): Promise<BookingRequest>;
    getCallerPendingBookings(): Promise<Array<BookingRequest>>;
    getCallerProcessingBookings(): Promise<Array<BookingRequest>>;
    getCallerStayHistory(): Promise<Array<StayRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHotelBookings(): Promise<Array<BookingRequest>>;
    getHotelPendingBookings(): Promise<Array<BookingRequest>>;
    getHotelProfile(hotelPrincipal: Principal): Promise<HotelProfile | null>;
    getHotelVisibility(hotel: Principal): Promise<PersistentHotelVisibility>;
    getHotelsByCountry(country: string): Promise<Array<HotelProfile>>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getPaymentRequest(id: string): Promise<PaymentRequest>;
    getTestingMode(): Promise<boolean>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    health(): Promise<HealthStatus>;
    isCallerAdmin(): Promise<boolean>;
    isCallerInvited(): Promise<boolean>;
    rejectBooking(id: bigint): Promise<void>;
    rejectPaymentRequest(id: string): Promise<void>;
    restoreAdminAccess(userProvidedToken: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveHotelProfile(profile: HotelProfile): Promise<void>;
    setHotelPaymentStatus(hotel: Principal, isPaid: boolean): Promise<void>;
    setHotelVisibility(hotel: Principal, isActive: boolean, isDummyHotel: boolean): Promise<void>;
    setTestingMode(enabled: boolean): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    updateRoomInventory(hotelPrincipal: Principal, room: RoomInventory): Promise<void>;
}
import type { AdminHotelVisibilityView as _AdminHotelVisibilityView, BookingRequest as _BookingRequest, BookingStatus as _BookingStatus, CreateStayRecordInput as _CreateStayRecordInput, HotelClassification as _HotelClassification, HotelProfile as _HotelProfile, HotelProfileWithPrincipal as _HotelProfileWithPrincipal, MapLocation as _MapLocation, PaymentOption as _PaymentOption, PaymentRequest as _PaymentRequest, PaymentStatus as _PaymentStatus, PersistentHotelVisibility as _PersistentHotelVisibility, RoomCurrency as _RoomCurrency, RoomInventory as _RoomInventory, StayRecord as _StayRecord, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminGetAllHotelVisibilityStats(): Promise<Array<AdminHotelVisibilityView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllHotelVisibilityStats();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllHotelVisibilityStats();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRecoveryDiagnostics(): Promise<AdminRecoveryDiagnostics> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRecoveryDiagnostics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRecoveryDiagnostics();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async checkInviteToken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkInviteToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkInviteToken(arg0);
            return result;
        }
    }
    async confirmBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBooking(arg0);
            return result;
        }
    }
    async confirmPaymentRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPaymentRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPaymentRequest(arg0);
            return result;
        }
    }
    async consumeInviteToken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.consumeInviteToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.consumeInviteToken(arg0);
            return result;
        }
    }
    async createBookingRequest(arg0: CreateBookingInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBookingRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBookingRequest(arg0);
            return result;
        }
    }
    async createPaymentRequest(arg0: bigint, arg1: string, arg2: string, arg3: PaymentOption): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentRequest(arg0, arg1, arg2, to_candid_PaymentOption_n17(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentRequest(arg0, arg1, arg2, to_candid_PaymentOption_n17(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createStayRecord(arg0: CreateStayRecordInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStayRecord(to_candid_CreateStayRecordInput_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStayRecord(to_candid_CreateStayRecordInput_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteRoomInventory(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoomInventory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoomInventory(arg0, arg1);
            return result;
        }
    }
    async generateHotelInviteToken(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateHotelInviteToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateHotelInviteToken(arg0);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAccountStatus(): Promise<AccountStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountStatus();
            return result;
        }
    }
    async getAllBookingRequests(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingRequests();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingRequests();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHotelsWithPrincipals(): Promise<Array<HotelProfileWithPrincipal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHotelsWithPrincipals();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHotelsWithPrincipals();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInviteTokens(): Promise<Array<InviteToken>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInviteTokens();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInviteTokens();
            return result;
        }
    }
    async getAllPaymentRequests(): Promise<Array<PaymentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPaymentRequests();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPaymentRequests();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getBookingRequest(arg0: bigint): Promise<BookingRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingRequest(arg0);
                return from_candid_BookingRequest_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingRequest(arg0);
            return from_candid_BookingRequest_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPendingBookings(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPendingBookings();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPendingBookings();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerProcessingBookings(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProcessingBookings();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProcessingBookings();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerStayHistory(): Promise<Array<StayRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStayHistory();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStayHistory();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotelBookings(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelBookings();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelBookings();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotelPendingBookings(): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelPendingBookings();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelPendingBookings();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotelProfile(arg0: Principal): Promise<HotelProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotelVisibility(arg0: Principal): Promise<PersistentHotelVisibility> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelVisibility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelVisibility(arg0);
            return result;
        }
    }
    async getHotelsByCountry(arg0: string): Promise<Array<HotelProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelsByCountry(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelsByCountry(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getPaymentRequest(arg0: string): Promise<PaymentRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentRequest(arg0);
                return from_candid_PaymentRequest_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentRequest(arg0);
            return from_candid_PaymentRequest_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestingMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestingMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestingMode();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async health(): Promise<HealthStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.health();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.health();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerInvited(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerInvited();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerInvited();
            return result;
        }
    }
    async rejectBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBooking(arg0);
            return result;
        }
    }
    async rejectPaymentRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPaymentRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPaymentRequest(arg0);
            return result;
        }
    }
    async restoreAdminAccess(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreAdminAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreAdminAccess(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveHotelProfile(arg0: HotelProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveHotelProfile(to_candid_HotelProfile_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveHotelProfile(to_candid_HotelProfile_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setHotelPaymentStatus(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHotelPaymentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHotelPaymentStatus(arg0, arg1);
            return result;
        }
    }
    async setHotelVisibility(arg0: Principal, arg1: boolean, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHotelVisibility(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHotelVisibility(arg0, arg1, arg2);
            return result;
        }
    }
    async setTestingMode(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTestingMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTestingMode(arg0);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async updateRoomInventory(arg0: Principal, arg1: RoomInventory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoomInventory(arg0, to_candid_RoomInventory_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoomInventory(arg0, to_candid_RoomInventory_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdminHotelVisibilityView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminHotelVisibilityView): AdminHotelVisibilityView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_BookingRequest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingRequest): BookingRequest {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_HotelClassification_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HotelClassification): HotelClassification {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_HotelProfileWithPrincipal_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HotelProfileWithPrincipal): HotelProfileWithPrincipal {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_HotelProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HotelProfile): HotelProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentOption_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentOption): PaymentOption {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRequest_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRequest): PaymentRequest {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_RoomCurrency_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomCurrency): RoomCurrency {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_RoomInventory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomInventory): RoomInventory {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_StayRecord_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StayRecord): StayRecord {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HotelProfile]): HotelProfile | null {
    return value.length === 0 ? null : from_candid_HotelProfile_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pricePerNight: bigint;
    currency: _RoomCurrency;
    promo: [] | [string];
    roomType: string;
    photos: Array<string>;
}): {
    pricePerNight: bigint;
    currency: RoomCurrency;
    promo?: string;
    roomType: string;
    photos: Array<string>;
} {
    return {
        pricePerNight: value.pricePerNight,
        currency: from_candid_RoomCurrency_n11(_uploadFile, _downloadFile, value.currency),
        promo: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.promo)),
        roomType: value.roomType,
        photos: value.photos
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    hotelName: string;
    hotel: Principal;
    createdAt: _Time;
    lastUpdated: _Time;
    room_type: string;
    checkInDate: _Time;
    guest: Principal;
    checkOutDate: _Time;
    guests: bigint;
}): {
    id: bigint;
    status: BookingStatus;
    hotelName: string;
    hotel: Principal;
    createdAt: Time;
    lastUpdated: Time;
    room_type: string;
    checkInDate: Time;
    guest: Principal;
    checkOutDate: Time;
    guests: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n24(_uploadFile, _downloadFile, value.status),
        hotelName: value.hotelName,
        hotel: value.hotel,
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated,
        room_type: value.room_type,
        checkInDate: value.checkInDate,
        guest: value.guest,
        checkOutDate: value.checkOutDate,
        guests: value.guests
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    profile: _HotelProfile;
}): {
    principal: Principal;
    profile: HotelProfile;
} {
    return {
        principal: value.principal,
        profile: from_candid_HotelProfile_n5(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hotel: Principal;
    visibility: _PersistentHotelVisibility;
    profile: [] | [_HotelProfile];
}): {
    hotel: Principal;
    visibility: PersistentHotelVisibility;
    profile?: HotelProfile;
} {
    return {
        hotel: value.hotel,
        visibility: value.visibility,
        profile: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PaymentStatus;
    option: _PaymentOption;
    user: Principal;
    reference: string;
    amount: bigint;
}): {
    id: string;
    status: PaymentStatus;
    option: PaymentOption;
    user: Principal;
    reference: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n32(_uploadFile, _downloadFile, value.status),
        option: from_candid_PaymentOption_n34(_uploadFile, _downloadFile, value.option),
        user: value.user,
        reference: value.reference,
        amount: value.amount
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    hotelName: string;
    hotel: Principal;
    createdAt: _Time;
    checkInDate: _Time;
    guest: Principal;
    checkOutDate: [] | [_Time];
}): {
    id: bigint;
    hotelName: string;
    hotel: Principal;
    createdAt: Time;
    checkInDate: Time;
    guest: Principal;
    checkOutDate?: Time;
} {
    return {
        id: value.id,
        hotelName: value.hotelName,
        hotel: value.hotel,
        createdAt: value.createdAt,
        checkInDate: value.checkInDate,
        guest: value.guest,
        checkOutDate: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.checkOutDate))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    logo: [] | [string];
    name: string;
    payment_instructions: [] | [string];
    location: _MapLocation;
    rooms: Array<_RoomInventory>;
    classification: _HotelClassification;
}): {
    country: string;
    logo?: string;
    name: string;
    payment_instructions?: string;
    location: MapLocation;
    rooms: Array<RoomInventory>;
    classification: HotelClassification;
} {
    return {
        country: value.country,
        logo: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.logo)),
        name: value.name,
        payment_instructions: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.payment_instructions)),
        location: value.location,
        rooms: from_candid_vec_n8(_uploadFile, _downloadFile, value.rooms),
        classification: from_candid_HotelClassification_n13(_uploadFile, _downloadFile, value.classification)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    EUR: null;
} | {
    IDR: null;
} | {
    SGD: null;
} | {
    USD: null;
}): RoomCurrency {
    return "EUR" in value ? RoomCurrency.EUR : "IDR" in value ? RoomCurrency.IDR : "SGD" in value ? RoomCurrency.SGD : "USD" in value ? RoomCurrency.USD : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    threeStar: null;
} | {
    oneStar: null;
} | {
    fiveStar: null;
} | {
    fourStar: null;
} | {
    jasmine: null;
} | {
    twoStar: null;
}): HotelClassification {
    return "threeStar" in value ? HotelClassification.threeStar : "oneStar" in value ? HotelClassification.oneStar : "fiveStar" in value ? HotelClassification.fiveStar : "fourStar" in value ? HotelClassification.fourStar : "jasmine" in value ? HotelClassification.jasmine : "twoStar" in value ? HotelClassification.twoStar : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "rejected" in value ? BookingStatus.rejected : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    confirmed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "rejected" in value ? PaymentStatus.rejected : "confirmed" in value ? PaymentStatus.confirmed : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dana: null;
} | {
    gopay: null;
} | {
    paypal: null;
}): PaymentOption {
    return "dana" in value ? PaymentOption.dana : "gopay" in value ? PaymentOption.gopay : "paypal" in value ? PaymentOption.paypal : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminHotelVisibilityView>): Array<AdminHotelVisibilityView> {
    return value.map((x)=>from_candid_AdminHotelVisibilityView_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingRequest>): Array<BookingRequest> {
    return value.map((x)=>from_candid_BookingRequest_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HotelProfileWithPrincipal>): Array<HotelProfileWithPrincipal> {
    return value.map((x)=>from_candid_HotelProfileWithPrincipal_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRequest>): Array<PaymentRequest> {
    return value.map((x)=>from_candid_PaymentRequest_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StayRecord>): Array<StayRecord> {
    return value.map((x)=>from_candid_StayRecord_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HotelProfile>): Array<HotelProfile> {
    return value.map((x)=>from_candid_HotelProfile_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoomInventory>): Array<RoomInventory> {
    return value.map((x)=>from_candid_RoomInventory_n9(_uploadFile, _downloadFile, x));
}
function to_candid_CreateStayRecordInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateStayRecordInput): _CreateStayRecordInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_HotelClassification_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HotelClassification): _HotelClassification {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_HotelProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HotelProfile): _HotelProfile {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentOption_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentOption): _PaymentOption {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_RoomCurrency_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomCurrency): _RoomCurrency {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_RoomInventory_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomInventory): _RoomInventory {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hotelName: string;
    hotel: Principal;
    checkInDate: Time;
    guest: Principal;
    checkOutDate?: Time;
}): {
    hotelName: string;
    hotel: Principal;
    checkInDate: _Time;
    guest: Principal;
    checkOutDate: [] | [_Time];
} {
    return {
        hotelName: value.hotelName,
        hotel: value.hotel,
        checkInDate: value.checkInDate,
        guest: value.guest,
        checkOutDate: value.checkOutDate ? candid_some(value.checkOutDate) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    logo?: string;
    name: string;
    payment_instructions?: string;
    location: MapLocation;
    rooms: Array<RoomInventory>;
    classification: HotelClassification;
}): {
    country: string;
    logo: [] | [string];
    name: string;
    payment_instructions: [] | [string];
    location: _MapLocation;
    rooms: Array<_RoomInventory>;
    classification: _HotelClassification;
} {
    return {
        country: value.country,
        logo: value.logo ? candid_some(value.logo) : candid_none(),
        name: value.name,
        payment_instructions: value.payment_instructions ? candid_some(value.payment_instructions) : candid_none(),
        location: value.location,
        rooms: to_candid_vec_n46(_uploadFile, _downloadFile, value.rooms),
        classification: to_candid_HotelClassification_n51(_uploadFile, _downloadFile, value.classification)
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pricePerNight: bigint;
    currency: RoomCurrency;
    promo?: string;
    roomType: string;
    photos: Array<string>;
}): {
    pricePerNight: bigint;
    currency: _RoomCurrency;
    promo: [] | [string];
    roomType: string;
    photos: Array<string>;
} {
    return {
        pricePerNight: value.pricePerNight,
        currency: to_candid_RoomCurrency_n49(_uploadFile, _downloadFile, value.currency),
        promo: value.promo ? candid_some(value.promo) : candid_none(),
        roomType: value.roomType,
        photos: value.photos
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentOption): {
    dana: null;
} | {
    gopay: null;
} | {
    paypal: null;
} {
    return value == PaymentOption.dana ? {
        dana: null
    } : value == PaymentOption.gopay ? {
        gopay: null
    } : value == PaymentOption.paypal ? {
        paypal: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomCurrency): {
    EUR: null;
} | {
    IDR: null;
} | {
    SGD: null;
} | {
    USD: null;
} {
    return value == RoomCurrency.EUR ? {
        EUR: null
    } : value == RoomCurrency.IDR ? {
        IDR: null
    } : value == RoomCurrency.SGD ? {
        SGD: null
    } : value == RoomCurrency.USD ? {
        USD: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HotelClassification): {
    threeStar: null;
} | {
    oneStar: null;
} | {
    fiveStar: null;
} | {
    fourStar: null;
} | {
    jasmine: null;
} | {
    twoStar: null;
} {
    return value == HotelClassification.threeStar ? {
        threeStar: null
    } : value == HotelClassification.oneStar ? {
        oneStar: null
    } : value == HotelClassification.fiveStar ? {
        fiveStar: null
    } : value == HotelClassification.fourStar ? {
        fourStar: null
    } : value == HotelClassification.jasmine ? {
        jasmine: null
    } : value == HotelClassification.twoStar ? {
        twoStar: null
    } : value;
}
function to_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RoomInventory>): Array<_RoomInventory> {
    return value.map((x)=>to_candid_RoomInventory_n47(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
